language: php

php:
  - 5.5
  - 5.6
  - 7

matrix:
  include:
    - php: 5.5
      env: dependencies="--prefer-lowest --prefer-stable"
    - php: 7
      env: dependencies="--prefer-lowest --prefer-stable"

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --no-interaction $dependencies

before_script:
  - mkdir -p src-tests/logs/
  - mkdir -p src-tests/coverage/

script:
  - stty cols 120
  - cd src-tests && ../vendor/bin/phpunit --coverage-clover ./logs/clover.xml
  - cd .. && vendor/bin/phpcs --standard=ruleset.xml
  - vendor/bin/php-cs-fixer fix --diff --dry-run

after_success:
  - travis_retry php vendor/bin/coveralls -v
