language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4snapshot'

services:
  - xvfb

env:
  global:
    - SELENIUM_VERSION="3.141.59"

matrix:
  include:
    - name: 'Lowest dependencies'
      php: 7.1
      env: dependencies="--prefer-lowest --prefer-stable"
    - name: 'Codestyle and static analysis'
      php: 7.3
      env: CHECK_CODESTYLE=1
      before_install:
        - phpenv config-rm xdebug.ini
      before_script: ~
      script:
        - composer codestyle:check
        - composer analyze
      after_success: ~

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --no-interaction $dependencies

before_script:
  - mkdir -p src-tests/logs/
  - mkdir -p src-tests/coverage/
  - mkdir chromedriver; CHROMEDRIVER_VERSION=$(wget -qO- "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"); wget -q -t 3 https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip; unzip chromedriver_linux64 -d chromedriver
  - CHROMEDRIVER_PATH=$PWD/chromedriver/chromedriver
  - SELENIUM_JAR=$(bin/steward install --no-interaction --no-ansi $SELENIUM_VERSION)
  - java -Dwebdriver.chrome.driver="$CHROMEDRIVER_PATH" -jar $SELENIUM_JAR -log selenium-server.log &
  - until $(echo | nc localhost 4444); do sleep 1; echo Waiting for selenium-server to start...; done;

script:
  - stty cols 120
  - cd src-tests && ../vendor/bin/phpunit --coverage-clover ./logs/clover.xml && cd ..

after_script:
  - cat selenium-server.log

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

cache:
  directories:
    - $HOME/.composer/cache

addons:
  chrome: stable
